<?php // views/reports/btrc/index.php
// Variables: $reports (array), $logs (array)
?>
<div class="page-header fade-in">
    <div>
        <h1 class="page-title">BTRC Reports</h1>
        <div class="page-breadcrumb">
            <i class="fa-solid fa-file-contract" style="color:var(--blue)"></i> Reports &rsaquo; BTRC DIS
        </div>
    </div>
    <div style="display:flex;gap:10px;">
        <a href="<?= base_url('reports/btrc/preview?month=' . date('n') . '&year=' . date('Y')) ?>"
           class="btn btn-secondary">
            <i class="fa-solid fa-eye"></i> Preview Current Month
        </a>
        <?php if (PermissionHelper::hasPermission('btrc_reports.generate')): ?>
        <a href="<?= base_url('reports/btrc/generate') ?>" class="btn btn-primary">
            <i class="fa-solid fa-plus"></i> Generate Report
        </a>
        <?php endif; ?>
    </div>
</div>

<?php if (!empty($_SESSION['success'])): ?>
<div class="card fade-in" style="padding:12px 18px;margin-bottom:14px;border-color:rgba(34,197,94,.4);background:rgba(34,197,94,.08);">
    <span style="color:var(--green);"><i class="fa-solid fa-check-circle"></i> <?= htmlspecialchars($_SESSION['success']) ?></span>
    <?php unset($_SESSION['success']); ?>
</div>
<?php endif; ?>
<?php if (!empty($_SESSION['error'])): ?>
<div class="card fade-in" style="padding:12px 18px;margin-bottom:14px;border-color:rgba(239,68,68,.4);background:rgba(239,68,68,.08);">
    <span style="color:var(--red);"><i class="fa-solid fa-circle-exclamation"></i> <?= htmlspecialchars($_SESSION['error']) ?></span>
    <?php unset($_SESSION['error']); ?>
</div>
<?php endif; ?>

<!-- Generated Reports -->
<div class="card fade-in" style="overflow:hidden;margin-bottom:20px;">
    <div style="padding:16px 20px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;">
        <h3 style="margin:0;font-size:14px;font-weight:700;">
            <i class="fa-solid fa-list" style="color:var(--blue);margin-right:6px;"></i>Generated Reports
        </h3>
        <span style="font-size:12px;color:var(--text2);"><?= count($reports) ?> report(s)</span>
    </div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Period</th>
                <th>Total Subscribers</th>
                <th>New Connections</th>
                <th>Disconnections</th>
                <th>Active</th>
                <th>Revenue (BDT)</th>
                <th>Status</th>
                <th>Generated By</th>
                <th>Generated At</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($reports)): ?>
            <tr>
                <td colspan="10" style="text-align:center;padding:32px;color:var(--text2);">
                    <i class="fa-solid fa-file-circle-xmark" style="font-size:24px;margin-bottom:8px;display:block;"></i>
                    No reports generated yet.
                    <?php if (PermissionHelper::hasPermission('btrc_reports.generate')): ?>
                    <a href="<?= base_url('reports/btrc/generate') ?>" style="color:var(--blue);">Generate your first report</a>
                    <?php endif; ?>
                </td>
            </tr>
            <?php else: ?>
            <?php foreach ($reports as $r): ?>
            <tr>
                <td style="font-weight:600;"><?= date('F Y', strtotime($r['report_period'])) ?></td>
                <td><?= number_format((int)$r['total_subscribers']) ?></td>
                <td style="color:var(--green);">+<?= number_format((int)$r['new_connections']) ?></td>
                <td style="color:var(--red);">-<?= number_format((int)$r['disconnections']) ?></td>
                <td><?= number_format((int)$r['active_subscribers']) ?></td>
                <td>৳ <?= number_format((float)$r['total_revenue'], 2) ?></td>
                <td>
                    <?php if ($r['status'] === 'final'): ?>
                    <span style="background:rgba(34,197,94,.15);color:var(--green);padding:2px 8px;border-radius:12px;font-size:11px;font-weight:600;">Final</span>
                    <?php else: ?>
                    <span style="background:rgba(234,179,8,.15);color:var(--yellow);padding:2px 8px;border-radius:12px;font-size:11px;font-weight:600;">Draft</span>
                    <?php endif; ?>
                </td>
                <td style="font-size:12px;"><?= htmlspecialchars($r['generated_by_name'] ?? '—') ?></td>
                <td style="font-size:12px;color:var(--text2);"><?= date('d M Y H:i', strtotime($r['generated_at'])) ?></td>
                <td>
                    <div style="display:flex;gap:6px;flex-wrap:wrap;">
                        <a href="<?= base_url('reports/btrc/view/' . $r['id']) ?>"
                           class="btn btn-secondary" style="padding:4px 10px;font-size:11px;">
                            <i class="fa-solid fa-eye"></i> View
                        </a>
                        <?php if (PermissionHelper::hasPermission('btrc_reports.export')): ?>
                        <a href="<?= base_url('reports/btrc/export/csv/' . $r['id']) ?>"
                           class="btn btn-secondary" style="padding:4px 10px;font-size:11px;color:var(--green);">
                            <i class="fa-solid fa-file-csv"></i> CSV
                        </a>
                        <a href="<?= base_url('reports/btrc/export/pdf/' . $r['id']) ?>"
                           target="_blank"
                           class="btn btn-secondary" style="padding:4px 10px;font-size:11px;color:var(--red);">
                            <i class="fa-solid fa-file-pdf"></i> PDF
                        </a>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
</div>

<!-- Generation Log -->
<div class="card fade-in" style="overflow:hidden;">
    <div style="padding:16px 20px;border-bottom:1px solid var(--border);">
        <h3 style="margin:0;font-size:14px;font-weight:700;">
            <i class="fa-solid fa-clock-rotate-left" style="color:var(--purple);margin-right:6px;"></i>Generation History
        </h3>
    </div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Action</th>
                <th>Period</th>
                <th>Format</th>
                <th>Performed By</th>
                <th>Date &amp; Time</th>
                <th>IP Address</th>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($logs)): ?>
            <tr>
                <td colspan="6" style="text-align:center;padding:24px;color:var(--text2);">No activity logged yet.</td>
            </tr>
            <?php else: ?>
            <?php foreach ($logs as $log): ?>
            <tr>
                <td>
                    <?php
                    $actionColors = [
                        'generated'    => 'var(--blue)',
                        'exported_csv' => 'var(--green)',
                        'exported_pdf' => 'var(--red)',
                        'previewed'    => 'var(--purple)',
                        'deleted'      => 'var(--red)',
                    ];
                    $actionIcons = [
                        'generated'    => 'fa-file-circle-plus',
                        'exported_csv' => 'fa-file-csv',
                        'exported_pdf' => 'fa-file-pdf',
                        'previewed'    => 'fa-eye',
                        'deleted'      => 'fa-trash',
                    ];
                    $color = $actionColors[$log['action']] ?? 'var(--text2)';
                    $icon  = $actionIcons[$log['action']] ?? 'fa-circle';
                    ?>
                    <span style="color:<?= $color ?>;font-size:12px;font-weight:600;">
                        <i class="fa-solid <?= $icon ?>"></i>
                        <?= ucfirst(str_replace('_', ' ', $log['action'])) ?>
                    </span>
                </td>
                <td style="font-weight:600;"><?= date('F Y', strtotime($log['report_period'])) ?></td>
                <td style="font-size:12px;text-transform:uppercase;"><?= htmlspecialchars($log['export_format'] ?? '—') ?></td>
                <td style="font-size:12px;"><?= htmlspecialchars($log['performed_by_name'] ?? '—') ?></td>
                <td style="font-size:12px;color:var(--text2);"><?= date('d M Y H:i', strtotime($log['performed_at'])) ?></td>
                <td style="font-size:12px;color:var(--text2);"><?= htmlspecialchars($log['ip_address'] ?? '—') ?></td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
</div>
